name: tea_shop_inventory
description: "Tea Shop Inventory & Sales Management App with offline support and cloud sync."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Local Database (Offline Storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Cloud Backend (Supabase)
  supabase_flutter: ^2.7.0
  
  # Authentication & Security
  crypto: ^3.0.5
  
  # Network & Connectivity
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^3.0.1
  
  # File Operations & Reports
  pdf: ^3.11.1
  csv: ^6.0.0
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  share_plus: ^10.0.2
  
  # Date & Time
  intl: ^0.20.1
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Utils
  uuid: ^4.5.1
  logger: ^2.4.0
  
  # Form validation
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation for Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

  # Linting
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true  # Enable code generation for localizations

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
